### ISSUE TITLE
Error "object" is impossible to work with.

### ISSUE THREAD

**Issue by timsim00** [salesforce-marketingcloud/FuelSDK-Node-REST#58]
Got this error when posting a new Campaign:

```
then [Error: Argument error, options.body.]  (see code below)
```
typeof(response) returned "object".  util.isArray(response) returned false.  Really couldn't do anything with the "object".  Trying to access response.Error was not possible.  I'd like to return the error back to the client but the only thing I could is print it to the console.

	this.parent.RestClient
		.post(options)
		.then(function(response) {
			//console.log('then',response); //<---- **** tricky result type when there's an error here.
			cb(response); 
		}.bind(this))
		.catch(function(err) {
			cb(err);  
		}.bind(this));

**Comment by vernak2539** [comment]
>typeof(response) returned "object". util.isArray(response) returned false. 

I would assume this is correct. Response should usually be an object, but it depends on the route you're calling and what it returns. Makes sense that `util.isArray` would return false because an array is different from an object, even though they are technically both objects.

As for your error, that should be handled in the `catch` statement if the library errored, or in the `.then` function if the API returns an error.

I would need more information in order to debug this. The response from the API being the key part.

I've been thinking of only resolving the promise on a status of 200 from the API, but this will first be integrated into the Auth client then here if it's viable.
